name: geolocator_fe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  logging: ^1.1.0
  flutter_screenutil: ^5.6.0
  cached_network_image: ^3.2.3
  geolocator: ^9.0.2
  flutter_map: ^3.1.0
  location: ^4.4.0
  latlong2: ^0.8.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - asset/img/
